[profile.default]
src = "contracts"
test = "test/foundry"
libs = ["lib"]
out = "foundry-out"
solc = "0.8.1"
optimizer = true
optimizer_runs = 200
remappings = ["@openzeppelin/contracts/=contracts/openzeppelin_l/contracts/"]
skip = ["openzeppelin_l/contracts/token/ERC721/**", "openzeppelin_l/contracts/interfaces/IERC4906.sol"]
